insert into products (id, name, price) values (1, 'Chocolate - Mi - Amere Semi', 85);
insert into products (id, name, price) values (2, 'Melon - Honey Dew', 76);
insert into products (id, name, price) values (3, 'Lambcasing', 78);
insert into products (id, name, price) values (4, 'Coffee Cup 12oz 5342cd', 7);
insert into products (id, name, price) values (5, 'Oxtail - Cut', 29);
insert into products (id, name, price) values (6, 'Wine - Hardys Bankside Shiraz', 89);
insert into products (id, name, price) values (7, 'Burger Veggie', 65);
insert into products (id, name, price) values (8, 'Yeast Dry - Fermipan', 96);
insert into products (id, name, price) values (9, 'Muffin Mix - Morning Glory', 99);
insert into products (id, name, price) values (10, 'Sprite, Diet - 355ml', 35);
insert into products (id, name, price) values (11, 'Coffee Beans - Chocolate', 79);
insert into products (id, name, price) values (12, 'Beef - Tenderloin', 6);
insert into products (id, name, price) values (13, 'Scallops - Live In Shell', 87);
insert into products (id, name, price) values (14, 'Olives - Kalamata', 23);
insert into products (id, name, price) values (15, 'Table Cloth 62x114 White', 6);
insert into products (id, name, price) values (16, 'Scallops 60/80 Iqf', 15);
insert into products (id, name, price) values (17, 'Coffee - Dark Roast', 99);
insert into products (id, name, price) values (18, 'Tomato - Green', 38);
insert into products (id, name, price) values (19, 'Wine - Red, Metus Rose', 8);
insert into products (id, name, price) values (20, 'Pastry - Chocolate Marble Tea', 93);
insert into products (id, name, price) values (21, 'Muffin Batt - Ban Dream Zero', 87);
insert into products (id, name, price) values (22, 'Dasheen', 89);
insert into products (id, name, price) values (23, 'Flower - Commercial Spider', 32);
insert into products (id, name, price) values (24, 'Radish', 24);
insert into products (id, name, price) values (25, 'Cake Circle, Paprus', 55);
insert into products (id, name, price) values (26, 'Ranchero - Primerba, Paste', 24);
insert into products (id, name, price) values (27, 'Bread - Roll, Italian', 33);
insert into products (id, name, price) values (28, 'Pastry - Chocolate Chip Muffin', 14);
insert into products (id, name, price) values (29, 'Cheese - Gorgonzola', 9);
insert into products (id, name, price) values (30, 'Ham - Smoked, Bone - In', 83);
